# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: circleci/node:16

    steps:
      - checkout
      - restore_cache:
          name: Restore package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --fronzen-lockfile --cache-folder ~/.cache/yarn
      - run:
          name: Run test
          command: |
            yarn run bootstrap
            yarn build
            yarn cmd:coverage
      - save_cache:
          name: Save package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# See: https://discuss.circleci.com/t/how-to-limit-pipeline-or-workflow-only-on-1-branch-or-how-to-prevent-pipeline-from-be-called-on-branch-without-config-yml/42254
workflows:
  build-workflow:
    jobs:
      - test:
          filters:
            branches:
              only: develop
